### ISSUE TITLE
Static Assets?

### ISSUE THREAD

**Issue by subdigital** [nestproject/Frank#6]
Thinking of writing a middleware to serve up static assets (unless something already exists?), but I'm unsure how this plugs into Frank. Can you point me in the right direction?

**Comment by subdigital** [comment]
Though it did occur to me that this should be done by nginx anyway.  Would still love to hear your response, just so I can learn how middleware works in general.

**Comment by kylef** [comment]
I think this is ultimately blocked until [NEP 2](https://github.com/nestproject/neps/blob/master/draft/0002-streamable-bodies.md) is finalised, and implemented in Curassow. Otherwise it won't be possible to serve binary files.

Frank doesn't have support for middleware, I wasn't sure what the best way to go forward would be. It might make sense to not couple this to Frank itself, but instead just provide an interface to wrap a nest application.

Examples:

``` swift
import Frank

let application: Frank.call
let middleware: RequestType -> ResponseType { request in
  if request... {
    // do some request pre-processing
  }

  if some case {
    return a new response
  }

  let response = application(request)
  if response.something {
    // post response processing
  }

  return response
}

serve(middleware)
```

There's a proof of concept middleware called [Padlock](https://github.com/nestproject/Padlock).

**Comment by subdigital** [comment]
Got it. This makes sense. Thanks for writing this up.
